name          'amateo/omd'
version       '1.0.4'
source        'UNKNOWN'
author        'amateo'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib'
